#!/usr/bin/env bash

if [[ -n "$AWS_ACCESS_KEY_ID" ]]; then
	ARG1="-e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
fi

if [[ -n "$AWS_SECRET_ACCESS_KEY" ]]; then
	ARG2="-e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
fi

docker run -it --rm $ARG1 $ARG2 -v "`pwd`":/project -v "$HOME/.aws":/root/.aws -w /project mesosphere/aws-cli $@