#!/usr/bin/env bash

declare -a vars=(
  "AWS_ACCESS_KEY_ID"
  "AWS_SECRET_ACCESS_KEY"
  "AWS_SESSION_TOKEN"
  "AWS_DEFAULT_REGION"
  "AWS_DEFAULT_OUTPUT"
)

ENVVAR=""
for var in "${vars[@]}"
do
  if [[ -n "${!var}" ]]; then
    ENVVAR="$ENVVAR -e $var=${!var}"
  fi
done

docker run -it --rm $ENVVAR -v "`pwd`":/project -v "$HOME/.aws":/root/.aws -w /project mikesir87/aws-cli $@
